= Que son los ansible facts

Los facts son datos de cada uno de los sistemas gestionados por ansible que son descubiertos automáticamente por ansible. La principal diferencia frente a las variables es que no son definidos al crear o ejecutar los playbooks y que siempre son individuales, no por grupos.

Típicamente tienen información del sistema, sistema operativo, dirección ip, y un largo etcetera. Todos los facts se guardan como una estructura de diccionario en la variable ansible_facts y se pueden usar como cualquier otra variable.


== Ver todos los facts de un sistema

1) A continuación vamos a crear un playbook que mostrará por pantalla todos los facts de nuestros sistemas gestionados.

[.lines_7]
[source,bash,subs="+macros,+attributes"]
----
- hosts: all
  tasks:
    - name: Mostrar todos los facts
      debug:
        var: ansible_facts
----

Y ejecutar el playbook. 

[.lines_7]
[source,bash,subs="+macros,+attributes"]
----
ansible-playbook -i hosts test_variables.yaml
----

== Acceder a un fact específico

Probemos como acceder a un fact concreto como elementos en un diccionario usando `["key"]`. Por ejemplo, uno que nos de el número de cores que tiene nuestro sistema.

[.lines_7]
[source,bash,subs="+macros,+attributes"]
----
- hosts: all
  tasks:
    - name: Mostrar todos los facts
      debug:
        var: ansible_facts["processor_count"]
----

Para facilitar su uso, muchos de estos facts del primer nivel de ansible_facts se pueden acceder directamente a traves del nombre "ansible_<nombre del fact>". Así, el siguiente playbook funciona correctamente:

[.lines_7]
[source,bash,subs="+macros,+attributes"]
----
- hosts: all
  tasks:
    - name: Mostrar todos los facts
      debug:
        var: ansible_processor_count
----


== Añadir facts durante la ejecución con `set_fact`

1) Es posible añadir un fact personalizado a los sistemas gestionados durante la ejecución de los playbooks utilizando tareas basadas en el módulo set_fact. Su uso es muy sencillo, simplemente tenemos que especificar el nombre del fact y su valor deseado. Este valor puede ser generado a partir de otras variables o facts existentes o añadidos con register.

[.lines_7]
[source,bash,subs="+macros,+attributes"]
----
- hosts: all
  tasks:
     - name: Obtner la versión del paquete binutils
       shell: rpm -q binutils
       register: binutils_package

    - name: Incluir fact binutils_version
      set_fact:
        binutils_version: "{{ binutils_package.stdout }}"

    - name: Mostrar el valor de binutils_version
      debug:
        var: binutils_version
----


== Uso de variables y facts en templates

1) Un caso de uso muy habitual con ansible es crear un archivo con un contenido determinado donde el contenido de este archivo dependerá de una variable o conjunto de variables. Para ello utilizamos el módulo template con un archivo patrón de entrada con el formato jinja2, donde las variables "{{ variable }}" serán sustituidos por el valor asignado en cada servidor.

A continuación veremos un ejemplo de archivo basado en template. Para ello creamos el directorio templates en la carpeta donde tengamos nuestros playbooks y creamos un archivo index.html.j2

[.lines_7]
[source,bash,subs="+macros,+attributes"]
----
Este servidor es {{ ansible_fqdn }}

El sistema operativo es {{ ansible_distribution }} {{ ansible_distribution_major_version }}

{% if informacion_detallada %}
Información adicional:
{% for nic in ansible_interfaces %}
Tarjeta de red: {{ nic }}
{% endfor %}
{% else %}
Información adicional deshabilitada
{% endif %}
----

Cread el siguiente playbook y probad a ejecutarlo con los valores `true` y `false` para la variable `informacion_detallada`:

[.lines_7]
[source,bash,subs="+macros,+attributes"]
----
- hosts: all
  vars:
    informacion_detallada: true
  tasks:
     - name: Cread el archivo /tmp/index.html
       template:
         src: index.html.j2
         dest: /tmp/index.html
----

