= Tags en ansible

Ansible permite a los usuarios ejecutar solo una parte de las tareas asignadas a un playbook utilizando tags.

== Añadir tags a las tareas

Para utilizar tags debemos añadir la opción `tags` a las tareas deseadas y añadir el nombre o nombres de las tags asignadas como una lista.

Algunos ejemplos:

[.lines_7]
[source,bash,subs="+macros,+attributes"]
----
- hosts: all
  tasks:
    - name: Tarea asignada a tag preparacion
      debug:
        msg: "Tag preparacion"
      tags:
        - preparacion

    - name: Tarea asignada a tag instalación
      debug:
        msg: "Tag instalacion"
      tags:
        - instalacion

    - name: Tarea asignada a tag configuración
      debug:
        msg: "Tag configuracion"
      tags:
        - configuracion

    - name: Tarea asignada a tag configuración e instalacion
      debug:
        msg: "Tag configuracion e instalacion"
      tags:
        - configuracion
        - instalacion

    - name: Tarea sin asignar a tags
      debug:
        msg: "Tarea sin asignar a tags"
----


== Seleccionar las tags ejecutar

Por defecto, cuando ejecutamos un playbook con ansible-playbook, se ejecutan *todas* las tags. Si queremos seleccionar las tags a ejecutar debemos emplear la opción `--tags <tag>` o `--tags tag1,tag2` si queremos ejecutar más de una tag.

También es posible ejecutar todas las tags menos una o un conjunto de tags usando la opción `--skip-tags <tag>` o `--skip-tags tag1,tag2`.

Algunos ejemplos:

[.lines_7]
[source,bash,subs="+macros,+attributes"]
----
$ ansible-playbook -i hosts --tags all test_tags.yaml

$ ansible-playbook -i hosts --tags preparacion test_tags.yaml

$ ansible-playbook -i hosts --tags preparacion,instalacion test_tags.yaml

$ ansible-playbook -i hosts --skip-tags preparacion,instalacion test_tags.yaml

----

Existen dos nombres de tags especiales, `always` y `never`. Una tarea que se añada a la tag `always` siempre será ejecutada incluso aunque no se incluya en la opción --tags a menos que se use --skip-tags always. Igualmente, las tareas asignadas a never no se ejecutarán nunca a menos que usemos --tags never.

